GET {{server}}/api/files/%5E%2Ba%7Cb

###

GET {{server}}/api/files/%2FData%2Fbotw%2Fmaterials%2Facorn.png

###

POST {{server}}/api/files/%2FData%2Fbotw%2Fmaterials%2Facorn.png
Content-Type: text/json

{
"sha256":"abcd"
}