POST {{server}}/api/files/$list_folder
Accept: application/x-yaml
Content-Type: application/x-yaml

Folder: "/Anime/名探偵コナン (1996)"
Recursive: true

###

GET {{server}}/api/files/%2Fwow.mkv
Accept: application/json

###

POST {{server}}/api/files/%5E
Accept: application/json
Content-Type: application/json

[
  "/Downloads/Anime/Naruto/[SOSG&52wy][Naruto_Shippuuden][221-222][Chs_Cht_Jpn][XviD_MP3][120FPS].mkv",
  "/wow.mkv"
]

###

GET https://pcs.baidu.com/rest/2.0/pcs/file?method=download&
    path=/apps/Pimix/%24%2F03D294C9ADD4A501C002349C42789946E28F0F9F291C3A1DEA897806CE4902B3.v1&
    access_token=21.a8e58f17f5408895afd36e80b5737171.2592000.1561213717.2187715413-1222350

###
GET http://localhost:5000/api/files/$list_folder?folder=/Fonts
Accept: application/json

###

DELETE http://{{server}}/api/files/%2Fwow.mkv


###

POST {{server}}/api/files/$move_server
Content-Type: application/json

{
  "from_server": "local:exs",
  "to_server": "local:kch"
}

###

POST {{server}}/api/files/$fix
Content-Type: application/json

{
  "fields_to_merge": [
    "Locations"
  ]
}

###

POST {{server}}/api/files/$add_location
Content-Type: application/json

{
  "id": "/Downloads/TV Shows/Shitsuren.Chocolatier.1080p.HDTV.x264.AAC-MED/Shitsuren.Chocolatier.Ep01.1080p.HDTV.x264.AAC-MED.mkv",
  "location": "local:1000",
  "verified": true
}

###

DELETE {{server}}/api/files/%2FTV%20Shows%2FCanada%2FMayday%20%282003%29%2FSeason%204%20%282007%29%2FMayday%20S04E01%20Miracle%20Escape%20%28Air%20France%20Flight%20358%29.mp4

### link

POST {{server}}/api/files/%5E
Content-Type: application/json

[
  "/Downloads/TV Shows/空中浩劫/S04.第四季/S04E01.第1集.法国航空358号.2005[中字].mp4",
  "abc"
]

### PATCH

PATCH {{server}}/api/files/%2FDownloads%2FAnime%2FDetective%20Conan%20The%20Bride%20of%20Halloween%20%5BBDMV%5D%2F%E5%90%8D%E6%8E%A2%E5%81%B5%E3%82%B3%E3%83%8A%E3%83%B3%20%E3%83%8F%E3%83%AD%E3%82%A6%E3%82%A3%E3%83%B3%E3%81%AE%E8%8A%B1%E5%AB%81%20DISC1%2FBDMV%2FAUXDATA%2Fsound.bdmv
Content-Type: application/json

{
  "adler32": "B4900DBE",
  "block_md5": [
    "7DFAB6BA795813C068390CCCDBE48FAC"
  ],
  "block_sha1": [
    "80B06E2A3590B90095E8CFE867B4254F02441AF3"
  ],
  "block_sha256": [
    "289A410CC806D6335255CC38059E55FF844B59537F686AA0463406C525FD504C"
  ],
  "crc32": "6658C819",
  "encryption_key": "8A96215A97354D6D8DA300F4897E9F39BFA822B437F1F21C9ADA0282E3FE943A",
  "id": "/Downloads/Anime/Detective Conan The Bride of Halloween [BDMV]/名探偵コナン ハロウィンの花嫁 DISC1/BDMV/AUXDATA/sound.bdmv",
  "md5": "7DFAB6BA795813C068390CCCDBE48FAC",
  "sha1": "80B06E2A3590B90095E8CFE867B4254F02441AF3",
  "sha256": "289A410CC806D6335255CC38059E55FF844B59537F686AA0463406C525FD504C",
  "size": 499288,
  "slice_md5": "9224281C021D49271AF8662A91573766"
}