### Get
GET {{server}}/api/configs/swisscom/default

### Add accounts
POST {{server}}/api/configs/swisscom/$add_accounts
Content-Type: application/x-yaml

Id: default
Pattern: /
Accounts: []

### Get
GET {{server}}/api/accounts/swisscom/p00b0

### Get Top Accounts
GET {{server}}/api/accounts/swisscom/$get_top_accounts
