### Refresh
GET {{server}}/api/tv_shows/$refresh?id=半沢直樹
Accept: application/x-yaml

### Refresh (POST)
POST {{server}}/api/tv_shows/$refresh
Accept: application/x-yaml
Content-Type: application/x-yaml

Id: 半沢直樹

### Add Single
POST {{server}}/api/tv_shows/アンサング・シンデレラ 病院薬剤師の処方箋
Accept: application/x-yaml
Content-Type: application/x-yaml

TmdbId: '106002'
Language: ja
PatternId: single_season
EpisodeIdWidth: 2

### Add multi
POST {{server}}/api/tv_shows/LEGAL HIGH
Accept: application/x-yaml
Content-Type: application/x-yaml

PatternId: multi_season
SeasonIdWidth: 2
EpisodeIdWidth: 2
TmdbId: '46234'
Language: ja

### Manual Fix of data
PATCH {{server}}/api/tv_shows/Westworld
Accept: application/x-yaml
Content-Type: application/x-yaml

Region: United States

### All
GET {{server}}/api/tv_shows/?query=$.*.id
Accept: application/x-yaml

### Get
GET {{server}}/api/tv_shows/LEGAL HIGH
Accept: application/x-yaml

### Format
GET {{server}}/api/tv_shows/$format?id=Friends&seasonId=9&episodeIds=23,24
Accept: application/x-yaml

### TMDB series
GET https://api.themoviedb.org/3/tv/47008?api_key=781b829a0214d68e3250f10aedbbc2d8&language=ja

### TMDB Season
GET https://api.themoviedb.org/3/tv/60573/season/1?api_key=781b829a0214d68e3250f10aedbbc2d8&language=en

###
