using Kifa.Subtitle.Ass;
using Xunit;

namespace Kifa.Subtitle.Tests.Ass;

public class AssScriptInfoSectionTests {
    [Fact]
    public void BasicTest() {
        var section = new AssScriptInfoSection();
        Assert.StartsWith("[Script Info]\nScript Type: V4.00+\n", section.ToString());
    }

    [Fact]
    public void WithValueTest() {
        var section = new AssScriptInfoSection {
            OriginalScript = "Kimi",
            Title = "Great!",
            ScriptType = "Special type"
        };
        Assert.StartsWith(
            "[Script Info]\nTitle: Great!\nOriginal Script: Kimi\nScript Type: Special type\n",
            section.ToString());
    }

    [Fact]
    public void WithUpdateDetailsTest() {
        var section = new AssScriptInfoSection {
            Title = "Great!",
            UpdateDetails = "Generated by Kifa.Tools.SubUtil"
        };
        Assert.Contains("Update Details: Generated by Kifa.Tools.SubUtil\n", section.ToString());

        var parsed = AssScriptInfoSection.Parse(null, section.ToString().Split("\n"));
        Assert.Equal("Generated by Kifa.Tools.SubUtil", parsed.UpdateDetails);
    }
}
