Pimix.Service.PimixService:
  PimixServerApiAddress: http://www.pimix.tk/api

Pimix.Api.Files.PimixFile:
  SubPathIgnorePattern: "\
  (^|/)(\\.|!|@)|\
  \\.(!qB|!ut|fdmdownload|crdownload|swp|idx2)$"
  FullPathIgnorePattern: "\
  ^/(Anime|TV Shows|Movies|Downloads/Bilibili)/.*\\.(xml|ass|srt)$"

Pimix.IO.FileStorageClient:
  ServerConfigs:
    any:
      Username: user
      Password: passw0rd
      Host: 192.168.1.101
      RemotePrefix: /nfs/Home
      Prefix: /home

Pimix.Apps.JobUtil.JobUtilCommand:
  ClientName: pimix
  HeartbeatInterval: 10:00

Pimix.Apps.PimixCommand:
  LoggingTargets:
  - console_full