Pimix.IO.FileStorageClient:
  ServerConfigs:
    server:
      Prefix:
      Username:
      Password:
      Host:
      RemotePrefix:

Pimix.Apps.PimixCommand:
  LoggingTargets:
  - console
  - file_full

Pimix.Apps.FileUtil.Commands.UploadCommand:
  TempLocation:
