### File info (11/21/2019 12:40:16)

GET https://storage.prod.mdl.swisscom.ch/metadata?p=L0RyaXZlL1Rlc3QvMjAxMC0xMS0yNS5iaW4=
Authorization: Bearer HyBvb22nQ6aOITwlY4cIEQ==

### Quota

GET https://storage.prod.mdl.swisscom.ch/usage
Authorization: Bearer 5ssY4QNsTB2Hu8vG5YoR3Q==

### File content

GET https://storage.prod.mdl.swisscom.ch/object?p=L0RyaXZlL1Rlc3QvMjAxMC0xMS0yNS5iaW4=
Authorization: Bearer 5ssY4QNsTB2Hu8vG5YoR3Q==
Range: bytes=1-10

###

GET https://storage.prod.mdl.swisscom.ch/metadata?p=L0RyaXZlL1Rlc3Qv
Authorization: Bearer 5ssY4QNsTB2Hu8vG5YoR3Q==

###
