### Add counter
POST {{server}}/api/moment_counter/users/$add_counter
Content-Type: application/x-yaml

UserId: Kimi
Counter:
  Title: 吉他练习
  Units:
    - minutes

### Remove counter
POST {{server}}/api/moment_counter/users/$remove_counter
Content-Type: application/x-yaml

UserId: Kimi
CounterId: Kimi/9

### Get Users
GET {{server}}/api/moment_counter/users/Kimi

### Get Counters
GET {{server}}/api/moment_counter/counters/