### Set
GET {{server}}/api/languages/german/words/Aussage?refresh=true

### Set
POST {{server}}/api/languages/german/words/kommen
Accept: application/x-yaml
Content-Type: application/x-yaml

{}

### Get
GET {{server}}/api/languages/german/verbs/wandern
Accept: application/x-yaml

{}

###
