### Refresh
GET {{server}}/api/tv_shows/$refresh?id=Silicon Valley
Accept: application/x-yaml

### Add Single
POST {{server}}/api/tv_shows/Miss PILOT
Accept: application/x-yaml
Content-Type: application/x-yaml

tmdb_id: '62045'
language: ja
pattern_id: single_season
episode_id_width: 2

### Add multi
POST {{server}}/api/tv_shows/深夜食堂
Accept: application/x-yaml
Content-Type: application/x-yaml

pattern_id: multi_season
season_id_width: 2
episode_id_width: 2
tmdb_id: '47008'
language: ja

### All
GET {{server}}/api/tv_shows/?query=$.*.id
Accept: application/x-yaml

### Get
GET {{server}}/api/tv_shows/深夜食堂
Accept: application/x-yaml

### List
GET {{server}}/api/tv_shows/$format_path?path=Miss PILOT
Accept: application/x-yaml

### TMDB episode
GET https://api.themoviedb.org/3/tv/1399?api_key=781b829a0214d68e3250f10aedbbc2d8&language=en

### TMDB Season
GET https://api.themoviedb.org/3/tv/60573/season/1?api_key=781b829a0214d68e3250f10aedbbc2d8&language=en

###
