GET {{server}}/api/memrise/german/

###

POST {{server}}/api/memrise/german/der+Abwart
Content-Type: application/x-yaml

Word: der Abwart
Level: B1
Form: -e
Synonym: (CH) = (D, A) Hausmeister
Feminine:
  Word: die Abwartin
  Level: B1
  Form: -nen
Meaning: caretaker, janitor
Examples:
  - Der Abwart hat mir geholfen, den Schrank in die Wohnung zu tragen.

###

POST {{server}}/api/memrise/courses/german
Content-Type: application/x-yaml

CourseName: goethe-zertifikat-wortliste
CourseId: '5941264'
DatabaseId: '7001191'
Columns:
  German: '1'
  English: '2'
  Form: '3'
  Pronunciation: '4'
  Examples: '5'
  Audios: '6'
Levels:
  A1: '13403229'
  A2: '13403230'
  B1: '13403231'
  M: '13403232'

###

GET {{server}}/api/memrise/courses/
